// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rdComplete
bool rdComplete(std::string string, bool is_code);
RcppExport SEXP _roxygen2_rdComplete(SEXP stringSEXP, SEXP is_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type string(stringSEXP);
    Rcpp::traits::input_parameter< bool >::type is_code(is_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdComplete(string, is_code));
    return rcpp_result_gen;
END_RCPP
}
// leadingSpaces
IntegerVector leadingSpaces(CharacterVector lines);
RcppExport SEXP _roxygen2_leadingSpaces(SEXP linesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lines(linesSEXP);
    rcpp_result_gen = Rcpp::wrap(leadingSpaces(lines));
    return rcpp_result_gen;
END_RCPP
}
// tokenise_preref
List tokenise_preref(CharacterVector lines, std::string file, int offset);
RcppExport SEXP _roxygen2_tokenise_preref(SEXP linesSEXP, SEXP fileSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(tokenise_preref(lines, file, offset));
    return rcpp_result_gen;
END_RCPP
}
// find_includes
CharacterVector find_includes(std::string path);
RcppExport SEXP _roxygen2_find_includes(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(find_includes(path));
    return rcpp_result_gen;
END_RCPP
}
// splitByWhitespace
std::vector<std::string> splitByWhitespace(std::string string);
RcppExport SEXP _roxygen2_splitByWhitespace(SEXP stringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type string(stringSEXP);
    rcpp_result_gen = Rcpp::wrap(splitByWhitespace(string));
    return rcpp_result_gen;
END_RCPP
}
// wrapString
std::string wrapString(std::string string, int width, int indent);
RcppExport SEXP _roxygen2_wrapString(SEXP stringSEXP, SEXP widthSEXP, SEXP indentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type string(stringSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type indent(indentSEXP);
    rcpp_result_gen = Rcpp::wrap(wrapString(string, width, indent));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP roxygen2_find_includes(SEXP);
RcppExport SEXP roxygen2_leadingSpaces(SEXP);
RcppExport SEXP roxygen2_rdComplete(SEXP, SEXP);
RcppExport SEXP roxygen2_splitByWhitespace(SEXP);
RcppExport SEXP roxygen2_tokenise_preref(SEXP, SEXP, SEXP);
RcppExport SEXP roxygen2_wrapString(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_roxygen2_rdComplete", (DL_FUNC) &_roxygen2_rdComplete, 2},
    {"_roxygen2_leadingSpaces", (DL_FUNC) &_roxygen2_leadingSpaces, 1},
    {"_roxygen2_tokenise_preref", (DL_FUNC) &_roxygen2_tokenise_preref, 3},
    {"_roxygen2_find_includes", (DL_FUNC) &_roxygen2_find_includes, 1},
    {"_roxygen2_splitByWhitespace", (DL_FUNC) &_roxygen2_splitByWhitespace, 1},
    {"_roxygen2_wrapString", (DL_FUNC) &_roxygen2_wrapString, 3},
    {"roxygen2_find_includes",     (DL_FUNC) &roxygen2_find_includes,     1},
    {"roxygen2_leadingSpaces",     (DL_FUNC) &roxygen2_leadingSpaces,     1},
    {"roxygen2_rdComplete",        (DL_FUNC) &roxygen2_rdComplete,        2},
    {"roxygen2_splitByWhitespace", (DL_FUNC) &roxygen2_splitByWhitespace, 1},
    {"roxygen2_tokenise_preref",   (DL_FUNC) &roxygen2_tokenise_preref,   3},
    {"roxygen2_wrapString",        (DL_FUNC) &roxygen2_wrapString,        3},
    {NULL, NULL, 0}
};

RcppExport void R_init_roxygen2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
